name = "celo-atari-games-api"
main = "src/index.ts"
compatibility_date = "2024-05-14"
compatibility_flags = ["nodejs_compat"]

[vars]
VITE_CHAIN_ID = "42220"
VITE_LEADERBOARD_ADDRESS = "0x2f8768b0444673Bb61C57DE1DC9f81411E195353"
VITE_SCORE_REGISTRY_ADDRESS_GAS_GOBBLER = "0xF26Ed81D52ae4A106344f5739D767e3D603f8370"
VITE_SCORE_REGISTRY_ADDRESS_BLOCK_BREAKER = "0xE27010F31B09F9666861098faC5cCB459DaD608D"
VITE_SCORE_REGISTRY_ADDRESS_STABLE_SPRINT = "0x51128D31536c712c9d29Cc1B139d415081971126"
VITE_SCORE_REGISTRY_ADDRESS_MENTO_INVADERS = "0x7aa5139F4c94297d4b58EC8C722E43CE0D3840a6"

[[kv_namespaces]]
binding = "SESSIONS"
id = "e3046d5d21f04b8abfbbc329eeda1c7e"

[[d1_databases]]
binding = "DB"
database_name = "celo-arcade-db"
database_id = "04a8ae6f-e91f-4c14-840d-de8dc74ce0fb"
